apiVersion: v1
kind: Service
metadata:
  name: kubenix-frontend
  labels:
    app: kubenix-frontend
spec:
  type: ClusterIP
  selector:
    app: kubenix-frontend
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kubenix-backend
  labels:
    app: kubenix-backend
spec:
  type: ClusterIP
  selector:
    app: kubenix-backend
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP

